### ISSUE TITLE
feature: support boiii

### ISSUE THREAD

**Issue by Aziks0** [Joshr520/BO3-Practice-Tool#1]
`boiii` added support for custom GSC scripts with https://github.com/momo5502/boiii/pull/689.

It would be nice to add support for `boiii`.

**Comment by Joshr520** [comment]
This is something I'd like to do however I don't believe I can given the tools I'm using. I'm relying on https://github.com/shiversoftdev/t7-compiler for custom c++ builtins to interface with the tool, and this doesn't work on boiii as of now.

I'm not really knowledgeable enough myself to make this work, so nothing I can do currently.

**Comment by Joshr520** [comment]
Well unfortunately it seems BOIII has been shut down so... closing this 😔

**Comment by Fantazstic** [comment]
@Joshr520 

Latest T7Compiler [supports BOIII injection](https://github.com/shiversoftdev/t7-compiler/commit/4e6af81da19e2be0fa1ea3a18a28caa8be732c7e), any chance the Practice Tool could be updated to handle the boiii.exe moduleName and adding the --boiii parameter to DebugCompiler.exe --inject commands? 

I tried changing the "BlackOps3.exe" moduleName directly to "boiii.exe", but the async process looking for BOIII runs in infinite loop, even though it says BOIII successfully found and some addresses (of unknown correctness) are printed to log. Not sure how to fix.

I think it's something to do with the "boiii.exe" module and how it runs "BlackOps3.exe" inside itself.

**Comment by Joshr520** [comment]
Sometime last year it was voted not to allow boiii for easter egg speedruns as its not maintained and some versions break how some stuff works in the game. After my initial post in this thread I also changed my stance on boiii to not allow it, so for those reasons I won't pursue making it work myself.
